### ISSUE TITLE
Config file for the Antmaze finetune 

### ISSUE THREAD

**Issue by I2Cold** [Lei-Kun/Uni-O4#2]
Hello, thank you for your great work and for providing the code!

I wanted to try running the code myself, especially in Antmaze. I found the config files for finetune for Gym and Adroit, but it seems like the AntMaze config files are missing. Could you possibly provide the config files for the Antmaze environment as well?

Thank you in advance.

**Comment by Lei-Kun** [comment]
Hi, thank you for your interest. 
Unfortunately, we haven't done the online fine-tuning experiments in this version. 
You could try using the config files for adroit tasks for the antmaze finetuning.
Best,
